name: Waka Readme

on:
  push:
    branches:
      - main
  schedule:
    # Runs every 2 hours
    - cron: "0 18 * * *"

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@v0.1.5
        with:
          GH_TOKEN: ${{ github.token }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
